# Generated by Django 5.2.7 on 2026-01-03 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_alert_alertnotificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotificationlog',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['sensor', 'status'], name='DHT_alert_sensor__ba1ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'next_retry_at'], name='DHT_alert_status_e518c9_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='DHT_alert_created_3eb0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotificationlog',
            index=models.Index(fields=['alert', 'sent_at'], name='DHT_alertno_alert_i_ab0079_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotificationlog',
            index=models.Index(fields=['channel', 'status'], name='DHT_alertno_channel_500d1f_idx'),
        ),
    ]
